### ISSUE TITLE
Replace the switch via simple arithmetic calculation

### ISSUE THREAD

**Issue by NebelFox** [thekrasich/SigmaSWDS#1]
https://github.com/thekrasich/SigmaSWDS/blob/86f7b9ca2bf896ee5cd3ee02fc78f15519a95ea7/Task3Ele/Household.cs#L185
`firstMonth = DateTimeFormatInfo.CurrentInfo.GetMonthName(quarter*3-2);`
`secondMonth = DateTimeFormatInfo.CurrentInfo.GetMonthName(quarter*3-1);`
`thirdMonth = DateTimeFormatInfo.CurrentInfo.GetMonthName(quarter*3);`

**Comment by thekrasich** [comment]
![image](https://user-images.githubusercontent.com/91842995/136835456-f4ebe1f0-cf11-4332-a05d-509f96cb9c2c.png)
